### ISSUE TITLE
Missing built-in exceptions

### ISSUE THREAD

**Issue by grit96** [dreadatour/Flake8Lint#63]
ConnectionError exceptions and other built-in exceptions give an undefined name error when linting.
A list of built-in exceptions can be found [here](https://docs.python.org/3/library/exceptions.html).

**Comment by dreadatour** [comment]
Please, specify correct "python_interpreter" in settings.
If your Python 3 interpreter could be found at /usr/local/bin/python3, set it in project settings like this:
```
	"settings": {
        "flake8lint": {
            "python_interpreter": "/usr/local/bin/python3"
        }
    }
```
(see documentation here: https://github.com/dreadatour/Flake8Lint#plugin-config and here: https://github.com/dreadatour/Flake8Lint#project-flake8-config):
```
    // set python interpreter (lint files for python >= 2.7):
    // - 'internal' for use internal Sublime Text 2 interpreter (2.6)
    // - 'auto' for search default system python interpreter (default value)
    // - absolute path to python interpreter for define another one
    //   use platform specific notation, i.e. "C:\\Anaconda\\envs\\py33\\python.exe"
    //   for Windows or then "/home/whatever/pythondist/python" for Unix
    "python_interpreter": "auto",
```

Otherwise default system python interpreter will be used (Python 2, most likely) and, of course, usage of Python 3 built-in exceptions would be incorrect.
