### ISSUE TITLE
ImportError: cannot import name lint

### ISSUE THREAD

**Issue by tdhopper** [dreadatour/Flake8Lint#70]
This plugin stopped working for me on ST2. If I look in console, I see this:

```
Reloading plugin /Users/tdhopper/Library/Application Support/Sublime Text 2/Packages/Python Flake8 Lint/Flake8Lint.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./Flake8Lint.py", line 22, in <module>
    from lint import lint, lint_external, load_flake8_config
ImportError: cannot import name lint
```

I removed and reinstalled it with package control, but that didn't seem to fix it.

**Comment by dreadatour** [comment]
Hi! I'll check it out today. Thank you for bug report!

**Comment by tdhopper** [comment]
Any progress on this? This stopped working for me.

**Comment by dreadatour** [comment]
Can't reproduce.

**Comment by AlexNisnevich** [comment]
I just encountered this issue myself, and it turned out it was because the [MarkdownEditing](https://packagecontrol.io/packages/MarkdownEditing) package was clobbering the `lint` package in the sublime plugin namespace. Removing the MarkdownEditing package fixed the issue.

Maybe you were encountering something similar, @tdhopper ? Try disabling other packages (particularly ones that offer "linting" functionality).
