### ISSUE TITLE
Multiline if statement marked as invalid if seconds row is aligned to text and not to bracket

### ISSUE THREAD

**Issue by hakib** [dreadatour/Flake8Lint#78]
according to the [indention section of PEP 8](https://www.python.org/dev/peps/pep-0008/#indentation) this block is valid

```
if (this_is_one_thing and
    that_is_another_thing):
    do_something()
```

However , using the linter in sublime
![sublime](http://i.imgur.com/jD16Vpq.png)

Is this valid ? 

Thanks, Haki.

**Comment by dreadatour** [comment]
Sorry for a long answer.

This code is not valid according to PEP8. This code is valid:

    if (this_is_one_thing and
            that_is_another_thing):
        do_something()

**Comment by hakib** [comment]
I'm pretty sure the example in the pep is similar to mine:

```
# No extra indentation.
if (this_is_one_thing and
    that_is_another_thing):
    do_something()
```

If you disagree you can close.

**Comment by dreadatour** [comment]
It seems you are right and this is valid and PEP8 does allow this, at least they say this is "acceptable option". I've found these discussions about this error:
- https://github.com/PyCQA/pep8/issues/386
- https://github.com/PyCQA/pep8/issues/126

You can simply add this error into global ignore list:

    "iignore": ["E129"]

[pep8](https://pypi.python.org/pypi/pep8) tool which is used for lint by default does not ignore this E129 error, there is a note about default ignore rules: https://github.com/dreadatour/Flake8Lint#note.

My Python Flake8 Lint plugin for ST by default ignore only one error: "D203", because of conflict with "D211". All other settings you could define as you wish :-)

Thank you for your answer, I've learned something new. Have a nice day!

**Comment by hakib** [comment]
OK, thanks man.
